### ISSUE TITLE
سلام 

### ISSUE THREAD

**Issue by fardinmardani** [mojtabaakbari221b/mojtabaakbari221b#1]
برای اینکه ی توکن از سایت sms.ir بگیریم باید چه کد پایتونی بزنیم جزییاتشو نمیدونم یک کد هم زدم ولی آدرسی که باید دوتا کد اهراز هویت رو بفرستم که از اون کد توکن رو بدست بیارم رو ندارم داخل پنل هم هرچی سوال میپرسم جواب درستی نمیگیرم ممنون میشم جواب بدین.

**Comment by mojtabaakbari221b** [comment]
سلام. توی پنل خودتون بخش برنامه نویسان --> لیست کلید های api میتونید بسازید

**Comment by fardinmardani** [comment]
سلام ممنونم این مشکل حل شد.
